# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Nikita Chernyi
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure Healthchecks path exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ healthchecks_uid }}"
    group: "{{ healthchecks_gid }}"
  with_items:
    - "{{ healthchecks_base_path }}"

- name: Ensure Healthchecks support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ healthchecks_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ healthchecks_uid }}"
    group: "{{ healthchecks_gid }}"
  with_items:
    - env
    - labels
    - local_settings.py

- name: Ensure Healthchecks container image is pulled
  community.docker.docker_image:
    name: "{{ healthchecks_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ healthchecks_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else healthchecks_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure Healthchecks container network is created
  community.general.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ healthchecks_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure Healthchecks systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/healthchecks.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ healthchecks_identifier }}.service"
    mode: "0644"
