# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Nikita Chernyi
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure Healthchecks paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ healthchecks_uid }}"
    group: "{{ healthchecks_gid }}"
  with_items:
    - "{{ healthchecks_base_path }}"
    - "{{ healthchecks_data_path }}"

- name: Ensure Healthchecks support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ healthchecks_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ healthchecks_uid }}"
    group: "{{ healthchecks_gid }}"
  with_items:
    - env
    - labels
    - local_settings.py
  register: healthchecks_support_files_result

- name: Run if self-building of Healthchecks container image is not enabled
  when: "not healthchecks_container_image_self_build | bool"
  block:
    - name: Ensure Healthchecks container image is pulled via community.docker.docker_image_pull
      when: devture_systemd_docker_base_container_image_pull_method == 'ansible-module'
      community.docker.docker_image_pull:
        name: "{{ healthchecks_container_image }}"
        pull: always
      register: healthchecks_container_image_pull_result_ansible_module
      retries: "{{ devture_playbook_help_container_retries_count }}"
      delay: "{{ devture_playbook_help_container_retries_delay }}"
      until: healthchecks_container_image_pull_result_ansible_module is not failed

    - name: Ensure Healthchecks container image is pulled via ansible.builtin.command
      when: devture_systemd_docker_base_container_image_pull_method == 'command'
      ansible.builtin.command:
        cmd: "{{ devture_systemd_docker_base_host_command_docker }} pull {{ healthchecks_container_image }}"
      register: healthchecks_container_image_pull_result_command
      retries: "{{ devture_playbook_help_container_retries_count }}"
      delay: "{{ devture_playbook_help_container_retries_delay }}"
      until: healthchecks_container_image_pull_result_command is not failed
      changed_when: "'Downloaded newer image' in healthchecks_container_image_pull_result_command.stdout"

- name: Run if self-building of Healthchecks container image is enabled
  when: "healthchecks_container_image_self_build | bool"
  block:
    - name: Ensure Healthchecks repository is present on self-build
      ansible.builtin.git:
        repo: "{{ healthchecks_container_image_self_build_repo }}"
        version: "{{ healthchecks_container_image_self_build_repo_version }}"
        dest: "{{ healthchecks_container_image_self_build_src_files_path }}"
        force: "yes"
      register: healthchecks_git_pull_results

    - name: Ensure Healthchecks container image is built
      community.docker.docker_image_build:
        name: "{{ healthchecks_container_image_self_build_name }}"
        dockerfile: docker/Dockerfile
        path: "{{ healthchecks_container_image_self_build_src_files_path }}"
        pull: true
        rebuild: "{{ 'always' if healthchecks_git_pull_results.changed | bool else 'never' }}"
      register: healthchecks_container_image_build_result

- name: Ensure Healthchecks container network is created via community.docker.docker_network
  when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
  community.docker.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ healthchecks_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"
  register: healthchecks_network_creation_result

- name: Ensure Healthchecks container network is created via ansible.builtin.command
  when: devture_systemd_docker_base_container_network_creation_method == 'command'
  ansible.builtin.command:
    cmd: >-
      {{ devture_systemd_docker_base_host_command_docker }} network create
      {% if devture_systemd_docker_base_ipv6_enabled %}--ipv6{% endif %}
      {{ devture_systemd_docker_base_container_networks_driver_options_string }}
      {{ healthchecks_container_network }}
  register: healthchecks_network_creation_result
  changed_when: healthchecks_network_creation_result.rc == 0
  failed_when: healthchecks_network_creation_result.rc != 0 and 'already exists' not in healthchecks_network_creation_result.stderr

- name: Ensure Healthchecks systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/healthchecks.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ healthchecks_identifier }}.service"
    mode: "0644"
  register: healthchecks_systemd_service_result

- name: Determine whether Healthchecks needs a restart
  ansible.builtin.set_fact:
    healthchecks_restart_necessary: >-
      {{
        healthchecks_support_files_result.changed | default(false)
        or healthchecks_systemd_service_result.changed | default(false)
        or healthchecks_container_image_pull_result_ansible_module.changed | default(false)
        or healthchecks_container_image_pull_result_command.changed | default(false)
        or healthchecks_container_image_build_result.changed | default(false)
      }}
