# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Healthchecks installation tasks
  tags:
    - setup-all
    - setup-healthchecks
    - install-all
    - install-healthchecks
  block:
    - name: Validate Healthchecks configuration
      when: healthchecks_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Healthchecks
      when: healthchecks_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Healthchecks uninstallation tasks
  tags:
    - setup-all
    - setup-healthchecks
  block:
    - name: Uninstall Healthchecks
      when: not healthchecks_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
