# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---


- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "item.old in vars"
  with_items:
    - {'old': 'healthchecks_systemd_required_systemd_services_list_default', 'new': 'healthchecks_systemd_required_services_list_default'}
    - {'old': 'healthchecks_systemd_required_systemd_services_list_auto', 'new': 'healthchecks_systemd_required_services_list_auto'}
    - {'old': 'healthchecks_systemd_required_systemd_services_list_custom', 'new': 'healthchecks_systemd_required_services_list_custom'}
    - {'old': 'healthchecks_systemd_wanted_systemd_services_list_default', 'new': 'healthchecks_systemd_wanted_services_list_default'}
    - {'old': 'healthchecks_systemd_wanted_systemd_services_list_auto', 'new': 'healthchecks_systemd_wanted_services_list_auto'}
    - {'old': 'healthchecks_systemd_wanted_systemd_services_list_custom', 'new': 'healthchecks_systemd_wanted_services_list_custom'}

- name: Fail if required Healthchecks settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - healthchecks_identifier
    - healthchecks_uid
    - healthchecks_gid
    - healthchecks_hostname
    - healthchecks_path_prefix
    - healthchecks_container_network
    - healthchecks_database_hostname
    - healthchecks_database_password
    - healthchecks_environment_variable_secret_key

- when: healthchecks_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required Healthchecks Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "vars[item] == ''"
      with_items:
        - healthchecks_container_labels_traefik_hostname
        - healthchecks_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `healthchecks_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if healthchecks_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          healthchecks_container_labels_traefik_path_prefix (`{{ healthchecks_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/healthchecks`).
      when: "healthchecks_container_labels_traefik_path_prefix != '/' and healthchecks_container_labels_traefik_path_prefix[-1] == '/'"
