# SPDX-FileCopyrightText: 2026 Suguru Hirahara
# SPDX-FileCopyrightText: 2026 spatterlight
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: healthchecks-${MOLECULE_DISTRO:-ubuntu2604}-default
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2604}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_result_format: yaml
  inventory:
    group_vars:
      all:
        # Helper variables
        healthchecks_debug_service_enabled: false

        # Variables for Healthchecks
        healthchecks_uid: 1000
        healthchecks_gid: 1000
        healthchecks_scheme: http
        healthchecks_hostname: localhost
        healthchecks_container_labels_traefik_enabled: false
        healthchecks_container_http_host_bind_port: 8000
        healthchecks_database_type: sqlite
        healthchecks_environment_variable_secret_key: lmxSDWFiwAz2apPWHuD0bd6SWumPBg8XEeQ2hxXoLFCwhjWNxysAom9Lahs2a5q7
  env:
    # Workaround for https://github.com/ansible/molecule/issues/4391
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/..:/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:~/.ansible/roles
verifier:
  name: ansible
